TensorFlow 2D encoding added
tatp22/multidim-positional-encoding pull request #4
Opened 2021-12-20 16:50 UTC by IRiViI

Hey, thanks for the code. I have most of my code in TensorFlow/Keras already so I converted your 2D encoding from torch to TensorFlow. I think other might also find this useful. 

Cheers

2021-12-20 17:36 UTC, tatp22 commented
Hey @IRiViI! Thanks for the contribution!

I agree, i think that others might find this useful as well. Ill make a quick change to this pr as well (mainly cleanups and more changes to the readme), and then I'll merge it.

2021-12-21 10:49 UTC, IRiViI commented
Cool, let me know when you are ready. I already found a bug in my code (which I just fixed).

2021-12-21 22:17 UTC, tatp22 requested changes
You know what, I can just redo the readme in another PR.

I just had one quick suggestion, theres a redundant import i think, but other than that it looks good :+1:. I'll merge it then

2021-12-21 22:17 UTC, tatp22 commented on positional_encodings/tf_positional_encodings.py
> +import tensorflow as tf
```suggestion
import tensorflow as tf
import numpy as np
```

2021-12-22 07:49 UTC, IRiViI commented
Oke cool, I only added a small part to the readme.

Well spotted the import redundancy. I guess that is what you get when copy pasting your code.

2021-12-22 07:54 UTC, IRiViI commented on positional_encodings/tf_positional_encodings.py
> +import tensorflow as tf
I resolved it in the editor.

2021-12-22 08:05 UTC, tatp22 commented
Cool, thank you! I'll merge this.

2021-12-22 08:05 UTC, merged

2021-12-22 09:39 UTC, IRiViI commented
Awesome! 

I could probably also do the same for 1D and 3D but I didn't need it though. 

There is one small difference in the outcome between the TensorFlow en PyTorch version. the outcome has a difference in the order of e-8 when I tested it. So I think it it due to rounding when the data was in 8 bit format or something. I don't care enough to track down where it happens but let me know if you think this should also be addressed. 

Cheers,

2021-12-22 10:37 UTC, tatp22 commented
Nah, I think thats fine. Actually, I can try myself to see if i can do the 1 and 3d version as a learning experience.

Also, i think that this small rounding error is fine, as it is not so much.